name: DEVXRDP – Super Persistent (Save on Cancel)

on:
  workflow_dispatch:
    inputs:
      ts_authkey:
        description: "Tailscale Auth Key"
        required: true
        type: string

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 90519200

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-Create Directories
        run: |
          $sec = ConvertTo-SecureString "Rdp!9Xq#2025" -AsPlainText -Force
          if (-not (Get-LocalUser -Name "DEVXRDP" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "DEVXRDP" -Password $sec -AccountNeverExpires
            Add-LocalGroupMember Administrators "DEVXRDP"
          }
          New-Item -Path "C:\Users\DEVXRDP\AppData\Local\Google\Chrome\User Data" -ItemType Directory -Force
          New-Item -Path "C:\PersistentData" -ItemType Directory -Force
          New-Item -Path "C:\Users\DEVXRDP\Downloads" -ItemType Directory -Force

      - name: Restore Session Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            C:\Users\DEVXRDP\AppData\Local\Google\Chrome\User Data
            C:\Users\DEVXRDP\Downloads
            C:\PersistentData
          key: rdp-v4-${{ github.run_id }}
          restore-keys: |
            rdp-v4-

      - name: Start Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -Wait -ArgumentList "/i","$env:TEMP\tailscale.msi","/quiet","/norestart"
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey "${{ inputs.ts_authkey }}" --hostname "DEVXRDP" --accept-dns=false

      - name: Setup RDP
        run: |
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: RDP Active Timer
        shell: powershell
        run: |
          $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4 | Select-Object -First 1
          Write-Host "IP: $ip | User: DEVXRDP | Pass: Rdp!9Xq#2025"
          
          # Timer loop (taaki cancel hone par ye step break ho jaye)
          try {
            Start-Sleep -Seconds 18000
          } finally {
            Write-Host "Session stopping... moving to save data."
          }

      # YE STEP SABSE ZAROORI HAI: Ye cancel hone par bhi chalega
      - name: Save Cache Always
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            C:\Users\DEVXRDP\AppData\Local\Google\Chrome\User Data
            C:\Users\DEVXRDP\Downloads
            C:\PersistentData
          key: rdp-v4-${{ github.run_id }}-${{ github.run_attempt }}
          
